#include "fe/engineCompileHelper.hpp"
#include "fe/subsystems/scripting/scriptManager.hpp"
#include <SFML/Window/Keyboard.hpp>
#include <SFML/Window/Mouse.hpp>

void fe::compileLuaKeybinds(fe::scriptManager *manager)
	{
		// Register C++ Enums
        manager->getEnumHandler().registerEnum("inputs",
            "A",            sf::Keyboard::A,
            "B",            sf::Keyboard::B,
            "C",            sf::Keyboard::C,
            "D",            sf::Keyboard::D,
            "E",            sf::Keyboard::E,
            "F",            sf::Keyboard::F,
            "G",            sf::Keyboard::G,
            "H",            sf::Keyboard::H,
            "I",            sf::Keyboard::I,
            "J",            sf::Keyboard::J,
            "K",            sf::Keyboard::K,
            "L",            sf::Keyboard::L,
            "M",            sf::Keyboard::M,
            "N",            sf::Keyboard::N,
            "O",            sf::Keyboard::O,
            "P",            sf::Keyboard::P,
            "Q",            sf::Keyboard::Q,
            "R",            sf::Keyboard::R,
            "S",            sf::Keyboard::S,
            "T",            sf::Keyboard::T,
            "U",            sf::Keyboard::U,
            "V",            sf::Keyboard::V,
            "W",            sf::Keyboard::W,
            "X",            sf::Keyboard::X,
            "Y",            sf::Keyboard::Y,
            "Z",            sf::Keyboard::Z,
            "0",            sf::Keyboard::Num0,
            "1",            sf::Keyboard::Num1,
            "2",            sf::Keyboard::Num2,
            "3",            sf::Keyboard::Num3,
            "4",            sf::Keyboard::Num4,
            "5",            sf::Keyboard::Num5,
            "6",            sf::Keyboard::Num6,
            "7",            sf::Keyboard::Num7,
            "8",            sf::Keyboard::Num8,
            "9",            sf::Keyboard::Num9,
            "Escape",       sf::Keyboard::Escape,
            "LCtrl",        sf::Keyboard::LControl,
            "LShift",       sf::Keyboard::LShift,
            "LAlt",         sf::Keyboard::LAlt,
            "LSystem",      sf::Keyboard::LSystem,
            "RCtrl",        sf::Keyboard::RControl,
            "RShift",       sf::Keyboard::RShift,
            "RAlt",         sf::Keyboard::RAlt,
            "RSystem",      sf::Keyboard::RSystem,
            "Menu",         sf::Keyboard::Menu,
            "LBracket",     sf::Keyboard::LBracket,
            "RBracket",     sf::Keyboard::RBracket,
            "Semicolon",    sf::Keyboard::SemiColon,
            "Comma",        sf::Keyboard::Comma,
            "Period",       sf::Keyboard::Period,
            "Quote",        sf::Keyboard::Quote,
            "Slash",        sf::Keyboard::Slash,
            "Backslash",    sf::Keyboard::BackSlash,
            "Tilde",        sf::Keyboard::Tilde,
            "Equal",        sf::Keyboard::Equal,
            "Hyphen",       sf::Keyboard::Dash,
            "Space",        sf::Keyboard::Space,
            "Enter",        sf::Keyboard::Return,
            "Backspace",    sf::Keyboard::BackSpace,
            "Tab",          sf::Keyboard::Tab,
            "PageUp",       sf::Keyboard::PageUp,
            "PageDown",     sf::Keyboard::PageDown,
            "End",          sf::Keyboard::End,
            "Home",         sf::Keyboard::Home,
            "Insert",       sf::Keyboard::Insert,
            "Delete",       sf::Keyboard::Delete,
            "NumPlus",      sf::Keyboard::Add,
            "NumDash",      sf::Keyboard::Subtract,
            "NumStar",      sf::Keyboard::Multiply,
            "NumSlash",     sf::Keyboard::Divide,
            "Left",         sf::Keyboard::Left,
            "Right",        sf::Keyboard::Right,
            "Up",           sf::Keyboard::Up,
            "Down",         sf::Keyboard::Down,
            "Num0",         sf::Keyboard::Numpad0,
            "Num1",         sf::Keyboard::Numpad1,
            "Num2",         sf::Keyboard::Numpad2,
            "Num3",         sf::Keyboard::Numpad3,
            "Num4",         sf::Keyboard::Numpad4,
            "Num5",         sf::Keyboard::Numpad5,
            "Num6",         sf::Keyboard::Numpad6,
            "Num7",         sf::Keyboard::Numpad7,
            "Num8",         sf::Keyboard::Numpad8,
            "Num9",         sf::Keyboard::Numpad9,
            "Pause",        sf::Keyboard::Pause,
            "LeftMouse",    sf::Mouse::Left + sf::Keyboard::KeyCount,
            "RightMouse",   sf::Mouse::Right + sf::Keyboard::KeyCount,
            "MiddleMouse",  sf::Mouse::Middle + sf::Keyboard::KeyCount,
            "XButton1",     sf::Mouse::XButton1 + sf::Keyboard::KeyCount,
            "XButton2",     sf::Mouse::XButton2 + sf::Keyboard::KeyCount
        );
	}
