#
# Try to find liblua.add_custom_command
# If found it will define:
#  LUA_LIBRARIES
#

set(OLD_CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES} ".a")

find_library(LUA_LIBRARY
				NAMES liblua lua
				PATHS ${PROJECT_SOURCE_DIR}/extlib/libs)

set(LUA_LIBRARIES ${LUA_LIBRARY})
set(CMAKE_FIND_LIBRARY_SUFFIXES ${OLD_CMAKE_FIND_LIBRARY_SUFFIXES})
